**Import Library & Load Dataset**

In [64]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Load dataset
df = pd.read_csv('StudentPerformanceFactors.csv')

# Tampilkan data
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70


**Cek Kolom Dataset**

In [65]:
# Melihat kolom dataset
df.columns

Index(['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender',
       'Exam_Score'],
      dtype='object')

**Preprocessing Data**

In [66]:
#cek missing value
df.isnull().sum()
df = df.dropna()

In [67]:
#Hapus kolom yang tidak digunakan
df = df[['Hours_Studied',
         'Previous_Scores',
         'Tutoring_Sessions',
         'Learning_Disabilities',
         'Exam_Score']]

In [68]:
#Membuat Academic Risk (Target)
def academic_risk(score):
    if score >= 80:
        return "Low"
    elif score >= 60:
        return "Medium"
    else:
        return "High"

df['academic_risk'] = df['Exam_Score'].apply(academic_risk)

In [69]:
#Menghapus Kolom Exam Score
df = df.drop('Exam_Score', axis=1)

In [70]:
#Encoding Data Kategorikal
from sklearn.preprocessing import LabelEncoder

le1 = LabelEncoder()
le2 = LabelEncoder()

df['Learning_Disabilities'] = le1.fit_transform(df['Learning_Disabilities'])
df['academic_risk'] = le2.fit_transform(df['academic_risk'])

print("Mapping label:")
for i, label in enumerate(le2.classes_):
    print(i, "=", label)

Mapping label:
0 = High
1 = Low
2 = Medium


**Cek Dataset Setelah Preprocessing**

In [71]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6378 entries, 0 to 6606
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Hours_Studied          6378 non-null   int64
 1   Previous_Scores        6378 non-null   int64
 2   Tutoring_Sessions      6378 non-null   int64
 3   Learning_Disabilities  6378 non-null   int64
 4   academic_risk          6378 non-null   int64
dtypes: int64(5)
memory usage: 299.0 KB


**Feature dan Target**

In [72]:
X = df[['Hours_Studied',
        'Previous_Scores',
        'Tutoring_Sessions',
        'Learning_Disabilities']]

y = df['academic_risk']

**NORMALISASI**

In [73]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

**Split Data**

In [74]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

**Model Teorema Bayes**

In [75]:
model = GaussianNB()

model.fit(X_train, y_train)

GaussianNB()

**Prediksi**

In [76]:
y_pred = model.predict(X_test)

**Evaluasi**

In [77]:
print("Accuracy :", accuracy_score(y_test, y_pred))

print("\nClassification Report")
print("Mapping label:")
for i, label in enumerate(le2.classes_):
    print(i, "=", label)
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

Accuracy : 0.9749216300940439

Classification Report
Mapping label:
0 = High
1 = Low
2 = Medium
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        17
           1       0.00      0.00      0.00         9
           2       0.98      1.00      0.99      1250

    accuracy                           0.97      1276
   macro avg       0.33      0.33      0.33      1276
weighted avg       0.96      0.97      0.97      1276


Confusion Matrix
[[   0    0   17]
 [   1    0    8]
 [   6    0 1244]]


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


**PROBABILITAS BAYES**

In [78]:
proba = model.predict_proba(X_test)

print("\nContoh Probabilitas (5 data pertama):")
print(proba[:5])


Contoh Probabilitas (5 data pertama):
[[6.51872407e-06 7.02647605e-03 9.92967005e-01]
 [3.85299517e-02 2.67168514e-02 9.34753197e-01]
 [3.13520829e-05 5.83245867e-03 9.94136189e-01]
 [3.41098210e-04 5.75296279e-03 9.93905939e-01]
 [1.06907971e-03 6.08176609e-03 9.92849154e-01]]
